# Generated by Django 2.2.5 on 2020-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course_image', verbose_name='Upload course image'),
        ),
    ]
